version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: devconnect
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"